[package]
name = "alfred-caniuse-rs"
version = "0.1.0"
authors = ["Rob Ede <robjtede@icloud.com>"]
edition = "2018"
license = "MIT"

[dependencies]
alfred = "4"
eyre = "0.6"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
ureq = { version = "2", features = ["json"] }
